# 站点基础
title: CTFHub Writeups
description: CTF学习笔记
baseurl: ""
url: "https://eclair-tracy.github.io"

# 自动文章链接规则
permalink: /:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# 分页
paginate: 10
paginate_path: "/page:num/"

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
